name = "menu-gk"
main = "src/worker.js"
compatibility_date = "2025-09-01"

[assets]
directory = "./public"
binding = "ASSETS"
# /resultados sirve resultados.html
html_handling = "auto-trailing-slash"

[[kv_namespaces]]
binding = "CHOICES"
id = "787e403110104782afe1e3bcf087bd79"
